name: Deploy Voll Med

on:
  push:
    branches: ["main"]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configura JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Verifica Docker Compose
      run: docker compose version

    - name: Roda Docker Compose
      run: docker compose up -d

    - name: List Docker images
      run: docker images
      
    - name: Deploy para EC2
      env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          USER: ubuntu
          HOST: 52.87.205.146
      run: |
          echo "$PRIVATE_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem

          docker save -o vollmed-api.tar vollmed-api-api

          scp -v -o StrictHostKeyChecking=no -i deploy_key.pem vollmed-api.tar $USER@$HOST:/home/ubuntu/
          echo "Arquivo vollmed-api.tar transferido."
          
          scp -v -o StrictHostKeyChecking=no -i deploy_key.pem init.sql $USER@$HOST:/home/ubuntu/
          echo "Arquivo init.sql transferido."
          
          scp -v -o StrictHostKeyChecking=no -i deploy_key.pem docker-compose-prod.yaml $USER@$HOST:/home/ubuntu/
          echo "Arquivo docker-compose-prod.yaml transferido."
          
          scp -v -o StrictHostKeyChecking=no -i deploy_key.pem script-deploy.sh $USER@$HOST:/home/ubuntu/
          echo "Arquivo script-deploy.sh transferido."

    - name: Executar script de deploy na EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i deploy_key.pem $USER@$HOST "\
          chmod +x script-deploy.sh && \
          ./script-deploy.sh"
